create extension if not exists pgcrypto;

create type app_user_role as enum (
  'manager',
  'customer'
);

create type app_platform_name as enum (
  'youtube',
  'instagram',
  'facebook',
  'linkedin',
  'x'
);

create type app_post_status as enum (
  'queued',
  'processing',
  'posted',
  'failed'
);

create type app_media_file_type as enum (
  'image',
  'video',
  'other'
);

create type app_schedule_repeat_type as enum (
  'daily',
  'weekly',
  'biweekly',
  'monthly',
  'yearly',
  'custom',
  'onetime'
);

create type app_automation_trigger as enum (
  'manual',
  'scheduler'
);

create type app_automation_run_status as enum (
  'running',
  'completed',
  'failed'
);

create type app_automation_post_status as enum (
  'processing',
  'posted',
  'failed'
);

create table user_profiles (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null unique,
  role app_user_role not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table user_profiles is 'People who can use the autopost dashboard.';
comment on column user_profiles.id is 'Unique user profile id.';
comment on column user_profiles.full_name is 'Display name shown in the app.';
comment on column user_profiles.email is 'User email used for login or identification.';
comment on column user_profiles.role is 'Access role in the app, such as manager or customer.';
comment on column user_profiles.is_active is 'Whether this user profile can access the app.';
comment on column user_profiles.created_at is 'Date and time when this user profile was created.';
comment on column user_profiles.updated_at is 'Date and time when this user profile was last updated.';

create table publishing_accounts (
  id text primary key,
  user_profile_id uuid references user_profiles(id) on delete set null,
  platform_name app_platform_name not null,
  account_name text not null,
  account_handle text not null,
  login_username text not null,
  login_note text,
  has_saved_password boolean not null default false,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint publishing_accounts_handle_per_platform unique (platform_name, account_handle)
);

comment on table publishing_accounts is 'Social media accounts that the app can publish through.';
comment on column publishing_accounts.id is 'Unique publishing account id, compatible with the current account_* JSON ids.';
comment on column publishing_accounts.user_profile_id is 'User profile that owns or manages this publishing account.';
comment on column publishing_accounts.platform_name is 'Social platform for this account.';
comment on column publishing_accounts.account_name is 'Friendly account name shown in the dashboard.';
comment on column publishing_accounts.account_handle is 'Public handle, page name, channel name, or profile identifier.';
comment on column publishing_accounts.login_username is 'Username or email used by automation when logging in.';
comment on column publishing_accounts.login_note is 'Optional helper note for login confirmation, recovery, or manual verification.';
comment on column publishing_accounts.has_saved_password is 'Whether an encrypted password exists for this account.';
comment on column publishing_accounts.is_enabled is 'Whether automation is allowed to publish through this account.';
comment on column publishing_accounts.created_at is 'Date and time when this publishing account was added.';
comment on column publishing_accounts.updated_at is 'Date and time when this publishing account was last updated.';

create table publishing_account_secrets (
  publishing_account_id text primary key references publishing_accounts(id) on delete cascade,
  encrypted_password text not null,
  encryption_method text not null default 'aes-256-gcm',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table publishing_account_secrets is 'Encrypted login secrets for publishing accounts. Plain passwords are never stored here.';
comment on column publishing_account_secrets.publishing_account_id is 'Publishing account that owns this encrypted secret.';
comment on column publishing_account_secrets.encrypted_password is 'Encrypted password used by the automation backend.';
comment on column publishing_account_secrets.encryption_method is 'Encryption method used for the encrypted password.';
comment on column publishing_account_secrets.created_at is 'Date and time when this secret was created.';
comment on column publishing_account_secrets.updated_at is 'Date and time when this secret was last updated.';

create table schedule_templates (
  id bigint generated by default as identity primary key,
  user_profile_id uuid references user_profiles(id) on delete set null,
  schedule_name text not null,
  publish_time time not null,
  timezone text not null default 'Asia/Kolkata',
  repeat_type app_schedule_repeat_type not null,
  end_date date,
  custom_cron text,
  is_active boolean not null default true,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_templates_custom_cron_required check (
    repeat_type <> 'custom' or nullif(trim(custom_cron), '') is not null
  ),
  constraint schedule_templates_onetime_end_date_required check (
    repeat_type <> 'onetime' or end_date is not null
  )
);

comment on table schedule_templates is 'Reusable publish schedules that can be assigned to posts.';
comment on column schedule_templates.id is 'Unique schedule template id.';
comment on column schedule_templates.user_profile_id is 'User profile that owns or manages this schedule.';
comment on column schedule_templates.schedule_name is 'Readable name for the schedule, such as Morning daily.';
comment on column schedule_templates.publish_time is 'Time of day when this schedule should publish.';
comment on column schedule_templates.timezone is 'Timezone used to interpret publish_time and end_date.';
comment on column schedule_templates.repeat_type is 'How often the schedule repeats.';
comment on column schedule_templates.end_date is 'Optional final date for this schedule, or the exact date for one-time schedules.';
comment on column schedule_templates.custom_cron is 'Cron expression used only when repeat_type is custom.';
comment on column schedule_templates.is_active is 'Whether this schedule can trigger publishing.';
comment on column schedule_templates.last_used_at is 'Last time this schedule triggered automation.';
comment on column schedule_templates.created_at is 'Date and time when this schedule was created.';
comment on column schedule_templates.updated_at is 'Date and time when this schedule was last updated.';

create table posts (
  id text primary key,
  user_profile_id uuid references user_profiles(id) on delete set null,
  publishing_account_id text not null references publishing_accounts(id) on delete restrict,
  platform_name app_platform_name not null,
  post_title text,
  post_caption text not null,
  post_status app_post_status not null default 'queued',
  azure_container_name text,
  azure_blob_path text,
  azure_blob_url text,
  original_file_name text,
  media_file_type app_media_file_type not null default 'other',
  mime_type text,
  file_extension text,
  file_size_bytes bigint,
  scheduled_publish_at timestamptz,
  schedule_template_id bigint references schedule_templates(id) on delete set null,
  published_at timestamptz,
  published_url text,
  failure_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint posts_file_size_not_negative check (file_size_bytes is null or file_size_bytes >= 0)
);

comment on table posts is 'Posts planned, queued, published, or failed by the autopost system. Media files are stored outside the database in Azure Storage.';
comment on column posts.id is 'Unique post id, compatible with the current upload_* JSON ids.';
comment on column posts.user_profile_id is 'User profile that owns or manages this post.';
comment on column posts.publishing_account_id is 'Publishing account that will publish or already published this post.';
comment on column posts.platform_name is 'Social platform where this post belongs.';
comment on column posts.post_title is 'Post title, mainly used for YouTube videos.';
comment on column posts.post_caption is 'Caption or description text sent to the social platform.';
comment on column posts.post_status is 'Current publishing state of this post.';
comment on column posts.azure_container_name is 'Azure Storage container name where the media file is stored.';
comment on column posts.azure_blob_path is 'Azure Storage blob path for the media file.';
comment on column posts.azure_blob_url is 'Azure Storage URL or signed URL for reading the media file.';
comment on column posts.original_file_name is 'Original file name uploaded or detected from a connected folder.';
comment on column posts.media_file_type is 'General file type used by the app, such as image or video.';
comment on column posts.mime_type is 'Browser or server detected MIME type, such as image/jpeg or video/mp4.';
comment on column posts.file_extension is 'File extension without the dot, such as jpg or mp4.';
comment on column posts.file_size_bytes is 'Media file size in bytes. The file itself is not stored in this table.';
comment on column posts.scheduled_publish_at is 'Exact date and time when this post should publish.';
comment on column posts.schedule_template_id is 'Reusable schedule assigned to this post.';
comment on column posts.published_at is 'Date and time when this post was successfully published.';
comment on column posts.published_url is 'Final social platform URL after publishing.';
comment on column posts.failure_message is 'Latest error message if publishing failed.';
comment on column posts.created_at is 'Date and time when this post was created.';
comment on column posts.updated_at is 'Date and time when this post was last updated.';

create table connected_folders (
  id text primary key,
  user_profile_id uuid references user_profiles(id) on delete set null,
  publishing_account_id text not null references publishing_accounts(id) on delete cascade,
  platform_name app_platform_name not null,
  folder_path text not null,
  last_scanned_at timestamptz,
  last_scan_error text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint connected_folders_one_per_account unique (publishing_account_id)
);

comment on table connected_folders is 'Local folders watched by the app for new media files to turn into posts.';
comment on column connected_folders.id is 'Unique folder connection id, compatible with the current folder_* JSON ids.';
comment on column connected_folders.user_profile_id is 'User profile that owns or manages this folder connection.';
comment on column connected_folders.publishing_account_id is 'Publishing account that receives posts from this folder.';
comment on column connected_folders.platform_name is 'Social platform connected to this folder.';
comment on column connected_folders.folder_path is 'Absolute local folder path watched by the backend.';
comment on column connected_folders.last_scanned_at is 'Date and time when this folder was last scanned.';
comment on column connected_folders.last_scan_error is 'Latest folder scan error, if any.';
comment on column connected_folders.is_active is 'Whether the backend should keep scanning this folder.';
comment on column connected_folders.created_at is 'Date and time when this folder was connected.';
comment on column connected_folders.updated_at is 'Date and time when this folder connection was last updated.';

create table folder_post_sources (
  post_id text primary key references posts(id) on delete cascade,
  connected_folder_id text not null references connected_folders(id) on delete cascade,
  relative_file_path text not null,
  file_fingerprint text not null,
  file_still_exists boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table folder_post_sources is 'Source file details for posts created from connected folders.';
comment on column folder_post_sources.post_id is 'Post created from this folder source file.';
comment on column folder_post_sources.connected_folder_id is 'Connected folder where the source file was found.';
comment on column folder_post_sources.relative_file_path is 'Path of the source file inside the connected folder.';
comment on column folder_post_sources.file_fingerprint is 'File fingerprint used to detect content changes.';
comment on column folder_post_sources.file_still_exists is 'Whether the source file still exists in the connected folder.';
comment on column folder_post_sources.created_at is 'Date and time when this folder source was first recorded.';
comment on column folder_post_sources.updated_at is 'Date and time when this folder source was last updated.';

create table automation_runs (
  id uuid primary key default gen_random_uuid(),
  started_by_user_profile_id uuid references user_profiles(id) on delete set null,
  run_trigger app_automation_trigger not null,
  run_status app_automation_run_status not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

comment on table automation_runs is 'Each manual or scheduled automation run started by the backend.';
comment on column automation_runs.id is 'Unique automation run id.';
comment on column automation_runs.started_by_user_profile_id is 'User profile that started the run, when started manually.';
comment on column automation_runs.run_trigger is 'Whether the run was started manually or by the scheduler.';
comment on column automation_runs.run_status is 'Overall status of the automation run.';
comment on column automation_runs.started_at is 'Date and time when the automation run started.';
comment on column automation_runs.finished_at is 'Date and time when the automation run finished.';
comment on column automation_runs.error_message is 'Top-level error message if the automation run failed.';
comment on column automation_runs.created_at is 'Date and time when this run record was created.';

create table automation_run_posts (
  id uuid primary key default gen_random_uuid(),
  automation_run_id uuid not null references automation_runs(id) on delete cascade,
  post_id text not null references posts(id) on delete cascade,
  publishing_account_id text not null references publishing_accounts(id) on delete restrict,
  platform_name app_platform_name not null,
  publish_status app_automation_post_status not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  failure_message text,
  created_at timestamptz not null default now()
);

comment on table automation_run_posts is 'Per-post publishing results inside an automation run.';
comment on column automation_run_posts.id is 'Unique automation run post id.';
comment on column automation_run_posts.automation_run_id is 'Automation run that attempted this post.';
comment on column automation_run_posts.post_id is 'Post attempted by automation.';
comment on column automation_run_posts.publishing_account_id is 'Publishing account used for this attempt.';
comment on column automation_run_posts.platform_name is 'Social platform used for this attempt.';
comment on column automation_run_posts.publish_status is 'Result status for this individual post attempt.';
comment on column automation_run_posts.started_at is 'Date and time when this post attempt started.';
comment on column automation_run_posts.finished_at is 'Date and time when this post attempt finished.';
comment on column automation_run_posts.failure_message is 'Error message if this post attempt failed.';
comment on column automation_run_posts.created_at is 'Date and time when this run-post record was created.';

create table post_status_history (
  id uuid primary key default gen_random_uuid(),
  post_id text not null references posts(id) on delete cascade,
  old_status app_post_status,
  new_status app_post_status not null,
  changed_by_user_profile_id uuid references user_profiles(id) on delete set null,
  change_reason text,
  changed_at timestamptz not null default now()
);

comment on table post_status_history is 'Audit trail of status changes for each post.';
comment on column post_status_history.id is 'Unique status history id.';
comment on column post_status_history.post_id is 'Post whose status changed.';
comment on column post_status_history.old_status is 'Previous post status before the change.';
comment on column post_status_history.new_status is 'New post status after the change.';
comment on column post_status_history.changed_by_user_profile_id is 'User profile that caused the status change, when known.';
comment on column post_status_history.change_reason is 'Short explanation for why the status changed.';
comment on column post_status_history.changed_at is 'Date and time when the status changed.';

create index publishing_accounts_platform_name_idx on publishing_accounts(platform_name);
create index posts_publishing_account_id_idx on posts(publishing_account_id);
create index posts_platform_name_idx on posts(platform_name);
create index posts_post_status_idx on posts(post_status);
create index posts_scheduled_publish_at_idx on posts(scheduled_publish_at);
create index posts_schedule_template_id_idx on posts(schedule_template_id);
create index connected_folders_publishing_account_id_idx on connected_folders(publishing_account_id);
create index automation_run_posts_automation_run_id_idx on automation_run_posts(automation_run_id);
create index automation_run_posts_post_id_idx on automation_run_posts(post_id);
create index post_status_history_post_id_idx on post_status_history(post_id);

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_user_profiles_updated_at
before update on user_profiles
for each row execute function set_updated_at();

create trigger set_publishing_accounts_updated_at
before update on publishing_accounts
for each row execute function set_updated_at();

create trigger set_publishing_account_secrets_updated_at
before update on publishing_account_secrets
for each row execute function set_updated_at();

create trigger set_schedule_templates_updated_at
before update on schedule_templates
for each row execute function set_updated_at();

create trigger set_posts_updated_at
before update on posts
for each row execute function set_updated_at();

create trigger set_connected_folders_updated_at
before update on connected_folders
for each row execute function set_updated_at();

create trigger set_folder_post_sources_updated_at
before update on folder_post_sources
for each row execute function set_updated_at();
